COMPRESSOR_API_ENTRY_POINT = "api"
COMPRESSOR_API_ENTRY_POINT_VERSION = "v1"

COMPRESSOR_API_ENTRY_POINT_PATH = "/" + "/".join([COMPRESSOR_API_ENTRY_POINT, COMPRESSOR_API_ENTRY_POINT_VERSION])

COMPRESSOR_API_ENTRY_POINT_COMPRESS_IMAGE_PATH = "/".join([COMPRESSOR_API_ENTRY_POINT_PATH, "compress_image"])
