CAPTIONING_API_ENTRY_POINT = "api"
CAPTIONING_API_ENTRY_POINT_VERSION = "v1"

CAPTIONING_API_ENTRY_POINT_PATH = "/" + "/".join([CAPTIONING_API_ENTRY_POINT, CAPTIONING_API_ENTRY_POINT_VERSION])

CAPTIONING_API_ENTRY_POINT_PREDICT_CAPTION_PATH = "/".join([CAPTIONING_API_ENTRY_POINT_PATH, "predict_caption"])
