services:
  minio:
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z-cpuv1
    container_name: minio
#    ports:
#      - "9000:9000"
#      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BROWSER_REDIRECT_URL=http://minio-monitor.${DOMAIN}
#      - MINIO_SERVER_URL=http://minio.${DOMAIN}
    command:
      server --console-address ":9001" /data
    volumes:
      - s3-disk:/data
    networks:
        - public-net
    labels:
      #### Labels define the behavior and rules of the traefik proxy for this container ####
      - "traefik.enable=true" # <== Enable traefik to proxy this container
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.routers.minio.rule=Host(`minio.${DOMAIN}`)"
      - "traefik.http.routers.minio.entrypoints=web"
#      - "traefik.http.routers.minio.middlewares=redirect@file"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"
     #### Labels for minio console ####
      - "traefik.http.routers.minio-console.service=minio-console"
      - "traefik.http.routers.minio-console.rule=Host(`minio-monitor.${DOMAIN}`)"
      - "traefik.http.routers.minio-console.entrypoints=web"
#      - "traefik.http.routers.minio-console.tls.certresolver=mytlschallenge"
      - "traefik.http.services.minio-console.loadbalancer.server.port=9001"
#     #### Labels for minio console secured ####
#      - "traefik.http.routers.minio-console-secured.service=minio-console"
#      - "traefik.http.routers.minio-console-secured.rule=Host(`minio-monitor.${DOMAIN}`)" # <== Your Domain Name for the https rule
#      - "traefik.http.routers.minio-console-secured.entrypoints=web-secured" # <== Defining entrypoint for https, **ref: line 31
#      - "traefik.http.routers.minio-console-secured.tls.certresolver=mytlschallenge" # <== Defining certsresolvers for https
#      - "traefik.http.services.minio-console-secured.loadbalancer.server.port=9001"
##      - "traefik.http.routers.minio-console-secured.tls=true" # <== Enable https for this container

volumes:
  s3-disk:
    name: minio-disk

networks:
    public-net:
        external: true
