services:
  minio:
    image: minio/minio:RELEASE.2024-04-06T05-26-02Z-cpuv1
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
    command: server --console-address ":9001" /data
    volumes:
      - s3-disk:/data

volumes:
  s3-disk:
    name: minio-disk
