services:
  api:
    container_name: image-processing-service-api
    image: image-processing-service-api
    build:
      context: ../../
      dockerfile: ./infra/processing_backend/Dockerfile
    env_file:
      - ../../.env
#    volumes:
#      - image-processing-service:/opt/processing_backend
    networks:
      - public-net
#    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.image-processing-service-api.rule=Host(`image-processing-service.${DOMAIN}`)"
      - "traefik.http.routers.image-processing-service-api.entrypoints=web"

#volumes:
#  image-processing-service:
#    external: false

networks:
  public-net:
    external: true
