services:
  api:
    container_name: image-processing-service-api
    image: image-processing-service-api
    build:
      context: ../../
      dockerfile: ./infra/processing_backend/Dockerfile
    env_file:
      - ../../.env
    networks:
      - public-net
    ports:
      - "8090:8090"

networks:
  public-net:
    external: true
