services:

#  processing-backend-service-api:
#    depends_on:
#      - image-captioning-service-api




volumes:
  image-captioning-service:
    external: false

networks:
  public-net:
    external: true
