services:
  api:
    container_name: image-compressor-service-api
    image: image-compressor-service-api
    build:
      context: ../../../
      dockerfile: ./processing_backend/infra/image_compressor/Dockerfile
    env_file:
      - ../../../.env
    ports:
      - "8092:8082"
