services:
  api:
    container_name: image-captioning-service-api
    image: image-captioning-service-api
    build:
      context: ../../../
      dockerfile: ./processing_backend/infra/image_captioning/Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]

    env_file:
      - ../../../.env
    ports:
      - "8091:8082"
    networks:
      - public-net

networks:
  public-net:
    external: true
