PROCESSING_API_ENTRY_POINT = "api"
PROCESSING_API_ENTRY_POINT_VERSION = "v1"

PROCESSING_API_ENTRY_POINT_PATH = "/" + "/".join([PROCESSING_API_ENTRY_POINT, PROCESSING_API_ENTRY_POINT_VERSION])

PROCESSING_API_ENTRY_POINT_INGEST_IMAGE_PATH = "/".join([PROCESSING_API_ENTRY_POINT_PATH, "ingest"])
PROCESSING_API_ENTRY_POINT_DELETE_IMAGE_PATH = "/".join([PROCESSING_API_ENTRY_POINT_PATH, "delete"])
PROCESSING_API_ENTRY_POINT_QUERY_PATH = "/".join([PROCESSING_API_ENTRY_POINT_PATH, "query"])
